variables:
  DOCKER_SEMREL: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  DOCKER_GIT: samueldebruyn/debian-git
  PREFIX_TAG_BUILDS: build
  PREFIX_TAG_RELEASE: release

stages:
  - Validate
  - BuildNumber
  - Build
  - Docker
  - Deploy
  - TagBuildNumber
  - TagVersion
  
# Templates
#######################################################################################

.build_template:
  stage: Build
  except:
    - branches

.build_number_template:
  stage: BuildNumber
  image: $DOCKER_GIT
  except:
    - branches
  artifacts:
    paths:
      - .build_number

.docker_template:
  stage: Docker
  image: docker:stable
  except:
    - branches
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.0-dind
  script:
    - BUILD_NUMBER=$(cat .build_number)
    - 'echo Building docker image for: $BUILD_NUMBER'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/$REGISTRY_PATH:$BUILD_NUMBER .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$REGISTRY_PATH:$BUILD_NUMBER  

.deploy_template:
  stage: Deploy
  except:
    - branches

## Merge templates
#######################################################################################

.build_mr_template:
  extends: .build_template
  except:
    - branches
  only:
    - merge_requests

.lint_mr_template:
  stage: Validate
  except:
    - branches
  only:
    - merge_requests

.test_mr_template:
  stage: Validate
  except:
    - branches
  only:
    - merge_requests

# Jobs
#######################################################################################

## Master jobs
#######################################################################################

BuildNumber:
  extends: .build_number_template
  only:
    - master
  script:
    - git rev-list --count HEAD > .build_number
    - 'echo Calculated build number: $(cat .build_number)'

TagBuildNumber:
  stage: TagBuildNumber
  image: $DOCKER_GIT
  only:
    - merge_requests
  script:
    - BUILD_NUMBER=$(cat .build_number)
    - 'echo Using build number: $BUILD_NUMBER'
    - git tag $PREFIX_TAG_BUILDS/$BUILD_NUMBER
    - git push https://gitlab-ci-token:$CI_PUSH_TOKEN@gitlab.com/$CI_PROJECT_PATH.git/ $PREFIX_TAG_BUILDS/$BUILD_NUMBER

TagVersion:
  stage: TagVersion
  image: $DOCKER_SEMREL
  variables:
    GSG_TAG_PREFIX: $PREFIX_TAG_RELEASE
  when: manual
  only:
    - merge_requests
  script: 
    - release next-version
